### ISSUE TITLE
unable to locate firmware MPLAB X project

### ISSUE THREAD

**Issue by ubidefeo** [BusPirate/Bus_Pirate#108]
hi folks

I have not been able to find the project for the firmware after my last pull (a couple months after I last built it in august).
did something change?

the BootLoader is available and I was able to build

any pointers on what happened?
I also updated MPLAB X to 5.05

thank you
ubi

**Comment by agatti** [comment]
Apologies for the delay in getting back to this - nothing really changed when it comes to project files.  Are you still having this issue even with a freshly checked out source tree?
