### ISSUE TITLE
Should non-firmware files be moved?

### ISSUE THREAD

**Issue by agatti** [BusPirate/Bus_Pirate#14]
Would it make sense to move the hardware schematics, gerber files, and CAD models to another repository?  There is plenty of stuff in there that is of limited usage for whoever wants to grab an updated firmware, after all.

**Comment by mikebdp2** [comment]
Yes, it could be a good idea to create it - any mirrors significantly reduce the chance of this information disappearing

**Comment by agatti** [comment]
Done with d12478f3f3d242c52f00da211adcda6b7c222c66.

**Comment by kallisti5** [comment]
Just chiming in that I 100% agree with this :-)

Great work so far @agatti !
