### ISSUE TITLE
Bus Pirate v3 does not enter BOOTLOADER anymore.

### ISSUE THREAD

**Issue by USBEprom** [BusPirate/Bus_Pirate#58]
As reference, seems that with firmwares built starting from repository dated July 16, 2017 and July 20, 2017, then is not possible to gain BOOTLOADER by issuing command "$".
By doing it then Bus Pirate v3 has a reset but it does not enter into the BOOTLOADER mode.
Firmwares built using option '1' and option 's'.

**Comment by agatti** [comment]
I don't have the necessary hardware to get this sorted out, but then I guess this is a duplicate of #38.
