### ISSUE TITLE
Terminal returning garbage characters

### ISSUE THREAD

**Issue by rehelmin** [BusPirate/Bus_Pirate#61]
Hello,

I just loaded the latest firmware today (commit id: feb479a056f1cf2559929a64e36c710a162c64f8) and when I open up the terminal I am getting mostly garbage characters returned from a BPv4.

![bpv4_fw7 1](https://user-images.githubusercontent.com/2601408/29993007-6900e320-8f6f-11e7-90c0-a6cdddd1fb1a.png)

I am running the screen terminal emulator on Mac OSX El Capitan.

Any idea what might be causing this? Rolling back to the 7.0 release seems to make everything happy again.

Thanks,
Ryan

**Comment by agatti** [comment]
Hrmm, does the commit before that one exhibit the same issue?  Things seem to work fine here, but I'll look into it once more.

**Comment by azolotko** [comment]
Having the same issue. I noticed that my hex files produced in `Firmware/busPirate.X/dist/BusPirate_v4/production` are much smaller (346K) than those in `package/BPv4-firmware` (962K). Could it be the case that we've missed some build step?

**Comment by azolotko** [comment]
c7776d5 is okay, and 6cea461 is not.

**Comment by agatti** [comment]
Thanks a lot for the feedback, I'll look at it right away!

**Comment by agatti** [comment]
@andersm is there anything that we are missing in your PR #60 ?  Seems like it might require a bit more work and/or figuring out whether certain settings are a prerequisite for the code to work.

**Comment by andersm** [comment]
I hadn't realized how XC16 handles function pointers on parts with more than 64KiB flash. I'll try to see if this can be worked around, otherwise the change will have to be reverted.

A dirty workaround might be to modify the linker script to place all strings within the first 64KiB.

**Comment by agatti** [comment]
Thanks, @andersm!  @azolotko, @rehelmin: can you please give this change a try and see if it makes things work for you?

**Comment by azolotko** [comment]
I've just tried 102260a and it looks good to me. Thanks.
