### ISSUE TITLE
Error compiling 

### ISSUE THREAD

**Issue by luizgribeiro** [BusPirate/Bus_Pirate#72]
Hello there.

I'm trying to compile the firmware from source since my BP v4 came without the UART mode.

I'm using xc16 version 1.33 with MPLAB v4.05 . When I try to build & Clean (like it says on dangerous prototypes documentation) the following is shown on display:

CLEAN SUCCESSFUL (total time: 58ms)
.
.
.
"/opt/microchip/xc16/v1.33/bin/xc16-gcc"   ../dp_usb/cdc.c  -o build/BusPirate_v4/production/_ext/1241334144/cdc.o  -c -mcpu=24FJ256GB106  -MMD -MF "build/BusPirate_v4/production/_ext/1241334144/cdc.o.d"        -g -omf=elf -DXPRJ_BusPirate_v4=BusPirate_v4  -no-legacy-libc    -mlarge-code -mlarge-data -O0 -I"../../microchip/include" -I".." -mcci -msmart-io=1 -Werror -Wall -msfr-warn=off -finline  -save-temps -finline
nbproject/Makefile-BusPirate_v4.mk:337: recipe for target 'build/BusPirate_v4/production/_ext/1472/base.o' failed
../base.c:42:9: error: unknown configuration setting: 'COE'
make[2]: *** [build/BusPirate_v4/production/_ext/1472/base.o] Error 255
make[2]: *** Waiting for unfinished jobs....
make[2]: Leaving directory '***************************************************'
nbproject/Makefile-BusPirate_v4.mk:90: recipe for target '.build-conf' failed
make[1]: Leaving directory '***************************************************'
nbproject/Makefile-impl.mk:39: recipe for target '.build-impl' failed
make[1]: *** [.build-conf] Error 2
make: *** [.build-impl] Error 2

BUILD FAILED (exit value 2, total time: 3s)

**Comment by agatti** [comment]
I just rebuilt the firmware with xc16 1.32 and MPLAB-X 4.0.1 and it worked as expected.  Let me update xc16 and see what happens then.

**Comment by agatti** [comment]
Fixed with a6202ec98938286131dd1b3ef8b6e119285ee584.

The COE configuration bit was supposed to enable (or rather disable in this case) clip-on emulation support, which seems to have been removed/renamed/whatever, as it was not really applicable to this project anyway.

**Comment by luizgribeiro** [comment]
Thanks very much.

I'll try to rebuild asap.
